export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        background: "#fcf8ff",
        "secondary-container": "#40c2fd",
        "on-tertiary-fixed": "#2f1500",
        "on-secondary-fixed": "#001e2c",
        "secondary-fixed-dim": "#7bd0ff",
        "on-surface-variant": "#474554",
        "outline-variant": "#c8c4d7",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-bright": "#fcf8ff",
        "tertiary-container": "#ac5d00",
        "on-secondary-fixed-variant": "#004c69",
        "on-primary-fixed": "#160066",
        "surface-container-highest": "#e5e0ed",
        "tertiary-fixed": "#ffdcc3",
        secondary: "#00668a",
        "surface-tint": "#5847d2",
        "on-secondary-container": "#004d6a",
        "secondary-fixed": "#c4e7ff",
        "surface-dim": "#dcd8e4",
        "surface-container": "#f0ecf8",
        "primary-fixed": "#e4dfff",
        outline: "#787586",
        tertiary: "#884800",
        "on-background": "#1c1b23",
        "on-tertiary-container": "#fff5f1",
        "primary-fixed-dim": "#c6bfff",
        "on-primary": "#ffffff",
        "surface-variant": "#e5e0ed",
        "inverse-on-surface": "#f3effb",
        "on-error-container": "#93000a",
        "on-primary-container": "#faf6ff",
        "inverse-surface": "#312f38",
        primary: "#5341cd",
        "surface-container-low": "#f6f2fe",
        "primary-container": "#6c5ce7",
        surface: "#fcf8ff",
        "surface-container-high": "#ebe6f2",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-surface": "#1c1b23",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#4029ba",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-primary": "#c6bfff",
        success: "#10b981",
        "on-success": "#ffffff",
        "success-container": "#d1fae5",
        "on-success-container": "#065f46",
      },
      spacing: {
        base_unit: "4px",
        margin_desktop: "32px",
        margin_mobile: "16px",
        gutter: "24px",
        container_max_width: "1280px",
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "badge-xs": ["12px", { lineHeight: "1", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "badge-xs": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
      },
    },
  },
};
